// Autogenerated by OmniLang Compiler (omc) v0.5.0
// Military Grade - High Stability Backend
#![allow(unused_assignments, unused_variables)]

fn print(val: i64) -> i64 {
  println!("{}", val);
  val
}

fn factorial(n: i64) -> i64 {
  let mut _stage = 0;
  loop {
    match _stage {
      0 => { // Label: start
        let _r1 = 2;
        let _r2 = if (n as i64) < (_r1 as i64) { 1 } else { 0 };
        if _r2 != 0 { _stage = 1; } else { _stage = 2; } continue;
      }
      1 => { // Label: if_true_1
        let _r3 = 1;
        return _r3;
      }
      2 => { // Label: if_false_2
        _stage = 3; continue;
      }
      3 => { // Label: if_end_3
        let _r4 = 1;
        let _r5 = (n as i64) - (_r4 as i64);
        let _r6 = factorial(_r5);
        let _r7 = (n as i64) * (_r6 as i64);
        return _r7;
      }
      _ => break,
    }
  }
  0
}

fn main() {
  let mut res = 0; // hoisted
  let mut _stage = 0;
  loop {
    match _stage {
      0 => { // Label: start
        let _r8 = 5;
        let _r9 = factorial(_r8);
        res = _r9;
        let _r10 = print(res);
        break;
      }
      _ => break,
    }
  }
}
