// Autogenerated by OmniLang Compiler (omc) v0.5.0
// Military Grade - High Stability Backend
#![allow(unused_assignments, unused_variables)]

fn print(val: i64) -> i64 {
  println!("{}", val);
  val
}

fn main() -> i64 {
  let mut _stage = 0;
  loop {
    match _stage {
      0 => { // Label: start
        let _r1 = 10;
        let _r2 = 10;
        let _r3 = if (_r1 as i64) == (_r2 as i64) { 1 } else { 0 };
        if _r3 != 0 { _stage = 1; } else { _stage = 2; } continue;
      }
      1 => { // Label: arm_body_0_4
        let _r4 = 1;
        _stage = 3; continue;
      }
      2 => { // Label: arm_check_1_3
        _stage = 3; continue;
      }
      3 => { // Label: match_end_1
        break;
      }
      _ => break,
    }
  }
  0
}

